# Generated by Django 4.0.4 on 2022-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('token_id', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('decimals', models.IntegerField()),
                ('thumbnail_url', models.URLField(null=True)),
                ('animation_url', models.URLField(null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('contract_name', models.CharField(max_length=40, null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('contract_address', 'token_id')},
            },
        ),
    ]
