# Generated by Django 4.0.4 on 2022-04-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asset_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contract_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='token_id',
            field=models.CharField(max_length=100),
        ),
    ]
