# Generated by Django 4.0.4 on 2022-04-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_category_alter_asset_contract_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
    ]
