# Generated by Django 4.0.4 on 2022-04-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_asset_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('contract_address', 'token_id')},
        ),
    ]
